version: 1
services:
  - type: web
    name: my-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegramBot.py # замените на имя вашего файла
    envVars:
      TELEGRAM_TOKEN: AIzaSyCrj3saz9DtSmuesXjHKLR7HIAxRJD3RrY  # замените на ваш токен